return {
    "simrat39/symbols-outline.nvim",

    keys = {
        {
            "<leader>sy",
            "<cmd>SymbolsOutline<cr>",
            desc = "Symbol Outline",
        },
    },

    config = function()
        require("symbols-outline").setup({})
    end,

    opts = {
        highlight_hovered_item = true,
        show_guides = true,
        auto_preview = false,
        position = "right",
        relative_width = true,
        width = 50,
        auto_close = false,
        show_numbers = true,
        show_relative_numbers = false,
        show_symbol_details = true,
        preview_bg_highlight = "Pmenu",
        autofold_depth = nil,
        auto_unfold_hover = true,
        fold_markers = { "", "" },
        wrap = false,
        keymaps = { -- These keymaps can be a string or a table for multiple keys
            close = { "<Esc>", "q" },
            goto_location = "<Cr>",
            focus_location = "o",
            hover_symbol = "<C-space>",
            toggle_preview = "K",
            rename_symbol = "r",
            code_actions = "a",
            fold = "h",
            unfold = "l",
            fold_all = "W",
            unfold_all = "E",
            fold_reset = "R",
        },
        lsp_blacklist = {},
        symbol_blacklist = {},
        symbols = {
            Array = { icon = "", hl = "@constant" },
            Boolean = { icon = "⊨", hl = "@boolean" },
            Class = { icon = "𝓒", hl = "@type" },
            Constant = { icon = "", hl = "@constant" },
            Constructor = { icon = "", hl = "@constructor" },
            Component = { icon = "", hl = "@function" },
            Enum = { icon = "ℰ", hl = "@type" },
            EnumMember = { icon = "", hl = "@field" },
            Event = { icon = "🗲", hl = "@type" },
            Field = { icon = "", hl = "@field" },
            File = { icon = "", hl = "@text.uri" },
            Fragment = { icon = "", hl = "@constant" },
            Function = { icon = "", hl = "@function" },
            Interface = { icon = "ﰮ", hl = "@type" },
            Key = { icon = "🔐", hl = "@type" },
            Method = { icon = "ƒ", hl = "@method" },
            Module = { icon = "", hl = "@namespace" },
            Namespace = { icon = "", hl = "@namespace" },
            Null = { icon = "NULL", hl = "@type" },
            Number = { icon = "#", hl = "@number" },
            Object = { icon = "⦿", hl = "@type" },
            Operator = { icon = "+", hl = "@operator" },
            Package = { icon = "", hl = "@namespace" },
            Property = { icon = "", hl = "@method" },
            String = { icon = "𝓐", hl = "@string" },
            Struct = { icon = "𝓢", hl = "@type" },
            TypeParameter = { icon = "𝙏", hl = "@parameter" },
            Variable = { icon = "", hl = "@constant" },
        },
    },
}
